video_manager/match/views.py
# -*- coding: utf-8 -*-
"""match views."""
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import login_required
from collections import namedtuple

import re

from video_manager.utils import flash_errors

from sqlalchemy import desc, asc

from .models import Match, Color, Fighter, MatchFighterMap, School, Tag, Tournament, Video
from .forms import CreateMatchForm, MatchSearchForm, UpdateMatchTagForm, UpdateMatchNoteForm, UpdateMatchFighterForm, MatchFighterForm

blueprint = Blueprint("match", __name__, url_prefix="/matches", static_folder="../static")


@blueprint.route("/data/tournaments")
@login_required
def tournaments():
    """List tournaments."""
    tournaments = list(map(lambda t: t.as_dict(), Tournament.query.order_by(desc(Tournament.start_date)).all()))
    return tournaments

@blueprint.route("/data/tags")
@login_required
def tags():
    """List tags."""
    tags = list(map(lambda t: t.as_dict(), Tag.query.all()))
    return tags

@blueprint.route("/data/fighters")
@login_required
def fighters():
    """List fighters."""
    fighters = list(map(lambda t: t.as_dict(), Fighter.query.all()))
    return fighters

@blueprint.route("/data/schools")
@login_required
def schools():
    """List schools."""
    schools = list(map(lambda t: t.as_dict(), School.query.all()))
    return schools


@blueprint.route("/", methods=["GET", "POST"])
@login_required
def index():
    """List matches."""
    def enforce_list(id_or_list):
        if type(id_or_list) == list:
            return id_or_list
        elif id_or_list == None:
            return []
        return [id_or_list]
    tournament_ids = enforce_list(request.args.getlist('tournament_ids'))
    tag_ids = enforce_list(request.args.getlist('tag_ids'))
    fighter_ids = enforce_list(request.args.getlist('fighter_ids'))
    school_ids = enforce_list(request.args.getlist('school_ids'))

    query = Match.query

    if tournament_ids != []:
        query = query.join(Tournament).filter(Tournament.id.in_(tournament_ids))
    if tag_ids != []:
        query = query.join(Match.tags).filter(Match.tags.any(Tag.id.in_(tag_ids)))
    if fighter_ids != []:
        query = query.join(Match.match_fighter_maps).filter(
            Match.match_fighter_maps.any(MatchFighterMap.fighter_id.in_(fighter_ids)))
    if school_ids != []:
        query = query.join(Match.match_fighter_maps).join(MatchFighterMap.fighter).filter(
            MatchFighterMap.fighter.has(Fighter.school_id.in_(school_ids)))

    matches = query.all()

    matches.sort(key=lambda m: m.tournament.start_date)

    return render_template("matches/index.html", matches=matches)

@ blueprint.route("/<match_id>", methods=["GET", "POST", "PATCH"])
@ login_required
def match(match_id):
    """Matches."""
    match = Match.query.filter_by(id=match_id).first()

    tag_form = UpdateMatchTagForm(request.form)
    tags = [(t.id, t.__repr__()) for t in Tag.query.order_by(asc(Tag.tag)).all()]
    tag_form.tags.choices = tags

    note_form = UpdateMatchNoteForm(request.form)
    template_fighter_form = MatchFighterForm(request.form, prefix='match_fighter_maps-_-')
    fighter_form = UpdateMatchFighterForm(request.form)

    fighters = [(t.id, t.__repr__()) for t in Fighter.query.order_by(asc(Fighter.name)).all()]
    colors = [(t.id, t.__repr__()) for t in Color.query.order_by(asc(Color.color)).all()]

    if request.method == 'POST':
        for mfm in fighter_form.match_fighter_maps:
            mfm.fighter.choices = fighters
            mfm.color.choices = colors

        if request.form.getlist('tags') and tag_form.validate_on_submit():
            match.update_tags(tag_form.tags.data)
        if request.form.getlist('notes') and note_form.validate_on_submit():
            match.update_notes(note_form.notes.data)
        if request.form.getlist('update-fighter') and fighter_form.validate_on_submit():
            match.update_match_fighter_maps(fighter_form.match_fighter_maps.data)
        return redirect(url_for('match.match', match_id=match_id))
    if request.method == 'GET':
        current_tags = [t.id for t in match.tags]
        fighter = namedtuple('Fighter', ['color', 'color_id', 'order', 'fighter', 'fighter_id'])
        current_fighters = [fighter(mfm.color, mfm.color_id, mfm.order, mfm.fighter.name,
                                    mfm.fighter_id) for mfm in match.match_fighter_maps]

        for fighter in current_fighters:
            fighter_form.match_fighter_maps.append_entry(fighter)

        for index in range(len(fighter_form.match_fighter_maps)):
            fighter_form.match_fighter_maps[index].fighter.choices = fighters
            fighter_form.match_fighter_maps[index].color.choices = colors
            fighter_form.match_fighter_maps[index].fighter.data = current_fighters[index].fighter_id
            fighter_form.match_fighter_maps[index].color.data = current_fighters[index].color_id
            fighter_form.match_fighter_maps[index].order.data = current_fighters[index].order

        template_fighter_form.fighter.choices = fighters
        template_fighter_form.color.choices = colors

        note_form.notes.data = match.notes
        tag_form.tags.data = current_tags

        match_fighter_maps = {}
        for mfm in match.match_fighter_maps:
            color = str(mfm.color.color)
            if color not in match_fighter_maps.keys():
                match_fighter_maps[color] = [mfm]
            else:
                match_fighter_maps[color].append(mfm)

        return render_template("matches/match.html", match=match, match_fighter_maps=match_fighter_maps, tag_form=tag_form, fighter_form=fighter_form, note_form=note_form, _template_fighter_form=template_fighter_form)


@ blueprint.route("/create/", methods=["GET", "POST"])
def create():
    """Create new match."""
    form = CreateMatchForm(request.form)

    tournaments = [(t.id, t.__repr__()) for t in Tournament.query.order_by(desc(Tournament.start_date)).all()]
    form.tournament.choices = tournaments
    if form.validate_on_submit():
        print(form.tournament.data)
        print(form.videos.data)
        urls = re.findall(r"([0-9A-Za-z_-]{11})", form.videos.data)
        videos = [Video(url=url) for url in urls]
        tournament = Tournament.query.filter_by(id=form.tournament.data[0]).first()
        match = Match.create(
            tournament=tournament,
            videos=videos,
        )
        flash("Match added")
        return redirect(url_for('match.match', match_id=match.id))
    else:
        flash_errors(form)
    return render_template("matches/create.html", form=form)

@ blueprint.route("/search/", methods=["GET", "POST"])
def search():
    """Filter matches"""
    form = MatchSearchForm(request.form)

    tags = [(t.id, t.__repr__()) for t in Tag.query.order_by(asc(Tag.tag)).all()]
    tournaments = [(t.id, t.__repr__()) for t in Tournament.query.order_by(desc(Tournament.start_date)).all()]
    fighters = [(t.id, t.__repr__()) for t in Fighter.query.order_by(asc(Fighter.name)).all()]
    schools = [(t.id, t.__repr__()) for t in School.query.order_by(asc(School.name)).all()]

    form.tags.choices = tags
    form.tournaments.choices = tournaments
    form.fighters.choices = fighters
    form.schools.choices = schools

    if form.validate_on_submit():
        return redirect(url_for("match.index", tournament_ids=form.tournaments.data, tag_ids=form.tags.data, fighter_ids=form.fighters.data, school_ids=form.schools.data))
    else:
        flash_errors(form)
    return render_template("matches/search.html", form=form)

video_manager/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")

video_manager/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

video_manager/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Kevin Farthing</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:farthing.kw@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

video_manager/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/favicon.ico') }}">
    <title>
      {% block page_title %} 
      hema_tracker
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

video_manager/templates/macros.html
{%- macro render_fighter_form(subform, index) %}
<div
  id="match_fighter_maps-{{ index }}-form"
  class="{% if index != '_' %}subform{% else %}visually-hidden{% endif %}"
  data-index="{{ index }}"
>
  <table id="match_fighter_maps-{{ index }}">
    <tbody>
      <tr>
        <th>{{subform.color.label}}</th>
        <td>{{subform.color}}</td>
      </tr>
      <tr>
        <th>{{subform.order.label}}</th>
        <td>{{subform.order}}</td>
      </tr>
      <tr>
        <th>{{subform.fighter.label}}</th>
        <td>{{subform.fighter}}</td>
      </tr>
    </tbody>
  </table>
  <a class="remove" href="#">Remove</a>
  <hr />
</div>
{%- endmacro %}

video_manager/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('public.home') }}">
      hema_tracker
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('public.home') }}"
            >Home
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if current_user and current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('match.search') }}"
            >Search Matches</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('match.index') }}"
            >Match Index</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('match.create') }}"
            >Create Match</a
          >
        </li>
        {% endif %}
      </ul>
      {% if current_user and current_user.is_authenticated %}
      <ul class="navbar-nav my-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.members') }}"
            >Logged in as {{ current_user.username }}</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.logout') }}">
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
          </a>
        </li>
      </ul>
      {% elif form %}
      <form
        class="form-inline"
        id="loginForm"
        method="POST"
        action="{{ url_for('public.home') }}"
        role="login"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="input-group mb-2 mr-sm-2">
          {{ form.username(placeholder="Username", class_="form-control mr-sm-1
          my-auto") }} {{ form.password(placeholder="Password",
          class_="form-control mr-sm-1 my-auto") }}
          <button class="btn btn-light btn-primary m-auto" type="submit">
            Login
          </button>
        </div>
      </form>
      <ul class="navbar-nav my-auto">
        <li class="nav-item">
          <a
            class="nav-link navbar-text"
            href="{{ url_for('public.register') }}"
            >Create account</a
          >
        </li>
      </ul>
      {% endif %}
    </div>
    <!-- /.navbar-collapse -->
  </div>
</nav>